# generated with zotgpt/anthropic
state_abbr_to_name={
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming"
}

# generated with zotgpt/anthropic
# FIPS to State Abbreviation mapping
fips_to_state = {
    "01": "AL", "02": "AK", "04": "AZ", "05": "AR", "06": "CA",
    "08": "CO", "09": "CT", "10": "DE", "11": "DC", "12": "FL",
    "13": "GA", "15": "HI", "16": "ID", "17": "IL", "18": "IN",
    "19": "IA", "20": "KS", "21": "KY", "22": "LA", "23": "ME",
    "24": "MD", "25": "MA", "26": "MI", "27": "MN", "28": "MS",
    "29": "MO", "30": "MT", "31": "NE", "32": "NV", "33": "NH",
    "34": "NJ", "35": "NM", "36": "NY", "37": "NC", "38": "ND",
    "39": "OH", "40": "OK", "41": "OR", "42": "PA", "44": "RI",
    "45": "SC", "46": "SD", "47": "TN", "48": "TX", "49": "UT",
    "50": "VT", "51": "VA", "53": "WA", "54": "WV", "55": "WI",
    "56": "WY", "60": "AS", "66": "GU", "69": "MP", "72": "PR",
    "78": "VI"
}

# Reverse mapping (State to FIPS)
state_to_fips = {v: k for k, v in fips_to_state.items()}

fips_to_full_name = {
    "01": {"abbr": "AL", "name": "Alabama"},
    "02": {"abbr": "AK", "name": "Alaska"},
    "04": {"abbr": "AZ", "name": "Arizona"},
    "05": {"abbr": "AR", "name": "Arkansas"},
    "06": {"abbr": "CA", "name": "California"},
    "08": {"abbr": "CO", "name": "Colorado"},
    "09": {"abbr": "CT", "name": "Connecticut"},
    "10": {"abbr": "DE", "name": "Delaware"},
    "11": {"abbr": "DC", "name": "District of Columbia"},
    "12": {"abbr": "FL", "name": "Florida"},
    "13": {"abbr": "GA", "name": "Georgia"},
    "15": {"abbr": "HI", "name": "Hawaii"},
    "16": {"abbr": "ID", "name": "Idaho"},
    "17": {"abbr": "IL", "name": "Illinois"},
    "18": {"abbr": "IN", "name": "Indiana"},
    "19": {"abbr": "IA", "name": "Iowa"},
    "20": {"abbr": "KS", "name": "Kansas"},
    "21": {"abbr": "KY", "name": "Kentucky"},
    "22": {"abbr": "LA", "name": "Louisiana"},
    "23": {"abbr": "ME", "name": "Maine"},
    "24": {"abbr": "MD", "name": "Maryland"},
    "25": {"abbr": "MA", "name": "Massachusetts"},
    "26": {"abbr": "MI", "name": "Michigan"},
    "27": {"abbr": "MN", "name": "Minnesota"},
    "28": {"abbr": "MS", "name": "Mississippi"},
    "29": {"abbr": "MO", "name": "Missouri"},
    "30": {"abbr": "MT", "name": "Montana"},
    "31": {"abbr": "NE", "name": "Nebraska"},
    "32": {"abbr": "NV", "name": "Nevada"},
    "33": {"abbr": "NH", "name": "New Hampshire"},
    "34": {"abbr": "NJ", "name": "New Jersey"},
    "35": {"abbr": "NM", "name": "New Mexico"},
    "36": {"abbr": "NY", "name": "New York"},
    "37": {"abbr": "NC", "name": "North Carolina"},
    "38": {"abbr": "ND", "name": "North Dakota"},
    "39": {"abbr": "OH", "name": "Ohio"},
    "40": {"abbr": "OK", "name": "Oklahoma"},
    "41": {"abbr": "OR", "name": "Oregon"},
    "42": {"abbr": "PA", "name": "Pennsylvania"},
    "44": {"abbr": "RI", "name": "Rhode Island"},
    "45": {"abbr": "SC", "name": "South Carolina"},
    "46": {"abbr": "SD", "name": "South Dakota"},
    "47": {"abbr": "TN", "name": "Tennessee"},
    "48": {"abbr": "TX", "name": "Texas"},
    "49": {"abbr": "UT", "name": "Utah"},
    "50": {"abbr": "VT", "name": "Vermont"},
    "51": {"abbr": "VA", "name": "Virginia"},
    "53": {"abbr": "WA", "name": "Washington"},
    "54": {"abbr": "WV", "name": "West Virginia"},
    "55": {"abbr": "WI", "name": "Wisconsin"},
    "56": {"abbr": "WY", "name": "Wyoming"}
}